name: Docker Image CI

on:
  push:
    tags:
      - 2.*
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print branch name
        run: |
          echo "Branch name is: ${{ github.head_ref }}"
          export DEFAULT_NAME=$(echo ${{ github.ref_name }} | tr / - )
          echo "Ref name is: ${{ DEFAULT_NAME }}"

          export TAG_NAME=$(echo "${{ github.head_ref }}" | tr / - | sed 's/^$/${{ DEFAULT_NAME }}/' )
          echo "Tag name is: $TAG_NAME"

      - name: Login to Github docker
        run: |
          echo $CR_PAT | docker login ghcr.io -u yonder-makers --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: Build docker image
        run: |
          export DEFAULT_NAME=$(echo ${{ github.ref_name }} | tr / - )
          export TAG_NAME=$(echo "${{ github.head_ref }}" | tr / - | sed 's/^$/${{ DEFAULT_NAME }}/' )
          docker build . --tag ghcr.io/yonder-makers/svelte-office-ui:$TAG_NAME

      - name: Push image to Github container registry
        run: |
          export DEFAULT_NAME=$(echo ${{ github.ref_name }} | tr / - )
          export TAG_NAME=$(echo "${{ github.head_ref }}" | tr / - | sed 's/^$/${{ DEFAULT_NAME }}/' )
          docker push ghcr.io/yonder-makers/svelte-office-ui:$TAG_NAME
